Vagrant.configure("2") do |config|
  config.vm.box = "k8s_master"
  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox" do |v|
    v.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    v.gui = true
  end
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "public_network", ip: "192.168.100.180", bridge: "Realtek 8821CE Wireless LAN 802.11ac PCI-E NIC"    
end